server:
  port: 8888

app:
  config:
    user: cfguser
    password: cfgpassword

spring:
  application:
    name: config
  cloud:
    profiles:
      active: native
    config:
      server:
        git:
          uri: https://github.com/adriannovegil/e-shop-config
        # Use the File System Backend to avoid git pulling. Enable "native" profile in the Config Server.
        native:
          searchLocations: file:///${GIT_REPO}

  security:
    user:
      name: ${app.config.user}
      password: ${app.config.password}  

# Logging
logging:
  level:
    root: info

---
spring:
  config:
    activate:
      on-profile: docker

  cloud:
    config:
      encrypt:
        enabled: true

app:
  config:
    user: ${CONFIG_SERVICE_USER}
    password: ${CONFIG_SERVICE_PASSWORD}
  logstash:
    host: logstash
