server:
  port: 8888

app:
  config:
    user: cfguser
    password: cfgpassword

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/adriannovegil/e-shop-config.git
          default-label: main     
  security:
    user:
      name: ${app.config.user}
      password: ${app.config.password}

# Logging
logging:
  level:
    root: info

---
spring:
  config:
    activate:
      on-profile: docker

  cloud:
    config:
      encrypt:
        enabled: true

app:
  config:
    user: ${CONFIG_SERVICE_USER}
    password: ${CONFIG_SERVICE_PASSWORD}
  logstash:
    host: logstash
