version: '3.9'

services:
  minio:
    image: minio/minio
    restart: always
    environment:
      MINIO_ACCESS_KEY: mystorage
      MINIO_SECRET_KEY: mystorage
      MINIO_REGION: eu-east
    volumes:
      - ./minio:/data
    command: server /data
    ports:
      - 8086:9000
    networks:
      - eshopnet

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    networks:
      - eshopnet
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 mystorage mystorage;
      /usr/bin/mc rm -r --force myminio/catalog-images;
      /usr/bin/mc mb myminio/catalog-images;
      /usr/bin/mc policy download myminio/catalog-images;
      exit 0;
      "

  imgproxy:
    image: darthsim/imgproxy:latest
    restart: always
    # Mount a volume as local image source
    #volumes:
    #- ./images:/opt # link to minio volume to imgproxy's /opt folder for local filesystem.
    environment:
      IMGPROXY_ALLOW_ORIGIN: '*'
      # you can link Minio volume to imgproxy and use as a local filesystem.
      #IMGPROXY_LOCAL_FILESYSTEM_ROOT: /opt
      IMGPROXY_USE_S3: 'true'
      IMGPROXY_S3_ENDPOINT: http://minio:9000
      AWS_ACCESS_KEY_ID: mystorage
      AWS_SECRET_ACCESS_KEY: mystorage
      AWS_REGION: eu-east
    links:
      - minio
    ports:
      - 8887:8080
    networks:
      - eshopnet

networks:
  eshopnet:
    driver: bridge
