version: '3.9'

services:
  config:
    build: ../infrastructure/config
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: docker,native
      CONFIG_SERVICE_USER: ${CONFIG_SERVICE_USER}
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
      CONFIG_KEYSTORE_PASSWORD: ${CONFIG_KEYSTORE_PASSWORD}
      CONFIG_KEY_PASSWORD: ${CONFIG_KEY_PASSWORD}
      EUREKA_USER: ${EUREKA_USER}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - 8888:8888
    networks:
      - eshopnet

  discovery:
    build: ../infrastructure/discovery
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVICE_USER: ${CONFIG_SERVICE_USER}
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
      EUREKA_USER: ${EUREKA_USER}
    depends_on:
      - config
    ports:
      - 8761:8761
    networks:
      - eshopnet

  gateway:
    build: ../infrastructure/gateway
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVICE_USER: ${CONFIG_SERVICE_USER}
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
      EUREKA_USER: ${EUREKA_USER}
    depends_on:
      - config
      - discovery
    ports:
      - 8080:8080
    networks:
      - eshopnet

networks:
  eshopnet:
    driver: bridge
